### ISSUE TITLE
[New Domain] 9Anime

### ISSUE THREAD

**Issue by Xodias** [MALSync/MALSync#1052]
New domain was recently created for 9anime
- Link: 9anime.center

**Comment by lolamtisch** [comment]
>New 9anime domain (Extension only)
>
>You will need to add the custom domain like below. There is a button Custom Domains in the settings. You possibly need to  restart the browser afterwards.
>
>9anime -> https://9anime.center/
>9anime -> https://9anime.club/
>
>Wiki: https://github.com/MALSync/MALSync/wiki/Custom-Domains

**Comment by Gilgamesh0028** [comment]
@lolamtisch Can confirm, the custom domain fix works.

Would be very nice to have this added to the list of 9anime global domains though.

**Comment by lolamtisch** [comment]
Yes it will be. But as we can only really release a new update max once a month. It will take a while.

**Comment by adityagupta1089** [comment]
![image](https://user-images.githubusercontent.com/11774081/155901870-1e1623b2-9367-4453-be4e-679ea63fbfc9.png)
I am not able to add the custom domain.

**Comment by henrik9999** [comment]
@adityagupta1089 send a screenshot of what you out into

**Comment by adityagupta1089** [comment]
![image](https://user-images.githubusercontent.com/11774081/155902001-888de568-e33e-4882-9dc9-0c4ee2072d6a.png)

**Comment by henrik9999** [comment]
@adityagupta1089 somehow the select is missing for you it should look like this
![unknown](https://user-images.githubusercontent.com/22085664/155902076-9de51981-3e52-4d87-bcd4-845290fb16c6.png)

**Comment by henrik9999** [comment]
@adityagupta1089 are you using Firefox Android

**Comment by adityagupta1089** [comment]
firefox linux

**Comment by farahnur42** [comment]
@adityagupta1089 Looks fine on my end, tested with Firefox Stable (97.0.1) and Firefox Nightly (99.0a1) on Arch (linux-zen 5.16.10, mesa 21.3.6-1 yadda yadda, I haven't updated in a couple days but that's about it)

**Comment by adityagupta1089** [comment]
I was able to add that by using pop-up mini mal, seems like the width for the widget is creating an issue, I tried increasing the height from 700px to 1000px or even 100%, but even that didn't help. Anyways it's added now.
Firefox 97.0.1 on Arch 5.16.11-arch1-1

**Comment by Fear3d** [comment]
Adding the custom domains actually didn't work for me, for some reason. I added them exactly as shown in this thread, and it did have me confirm permissions for the new domains, so it seemed like it was going to work... but then nothing happened when I went to watch anime on those domains. It didn't show the MAL data on the anime page, and no syncing happened.

It doesn't really matter anymore, since 9anime already stopped using those domains, but I had my progress go out of sync for several shows during that time, so I'd like to try to figure out why it wasn't working, in case there is a similar situation in the future. Anyone have any ideas on why it wasn't working for me? I had entered it exactly like the screenshot that @henrik9999 posted. I'm on Firefox on Windows 10, in case that matters.

Also, to get around the once a month update limit, would it be feasible for you guys to make it so MALSync downloads a domain list from Github every time it starts up, or something along those lines? That way, you wouldn't need a hard update in order to change the domains.

**Comment by lolamtisch** [comment]
@Fear3d 
With the next release the domain lists will be loaded from our server. But it will work exactly the same as it is now just that you dont have to enter the domains by hand and you only need to click one button on the custom domain page to add them all.
Unfortunally domains that get added after a release have a different format and the code has to injected by hand. We still could not reproduce why it does work for some people. Most of the time a browser restart fixes it.
