### ISSUE TITLE
Adventure Time is NOT an anime :(

### ISSUE THREAD

**Issue by Lorphex** [MALSync/MALSync#1054]
I've been rewatching Adventure Time on Hulu and every time I start a new episode, I get a pop-up to start watching. Dunno if there's a feature I'm missing to blacklist this or what, but it's really annoying, especially when I'm binging and each episode is only 10 minutes.

**Steps to reproduce the behavior:**

**Additional information:**
 - Browser: firefox
 - Type: Extension

**Comment by farahnur42** [comment]
@Lorphex Looking at the Hulu implementation in MALSync I'm guessing it's because Adventure Time has Animation in it's list of genres (as it should be, which MALSync does check for as a genre to detect whether it should be loaded or not), and I think that's probably because there are some anime out there that Hulu only tags as Animation and not also Anime.

In any case if you want to get rid of that popup and you don't want to disable MALSync for Hulu then I would recommend adding the title as a local storage entry. To do that, select no entry on MAL in the correction menu  (default hotkey for pulling that up is C, if it doesn't work then I would recommend changing the hotkey to something like Alt + C) and then press Yes on Start Watching once it shows up, it will just get logged to a local storage entry and not to anywhere else.
