### ISSUE TITLE
extension crashing my browser

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#1093]
**Describe the bug**

The MAL sync extension is crashing my Chrome browser
**Steps to reproduce the behavior:**

**Additional information:**
 - Browser: Chrome
 - Type: Extension
 - Url:

**Comment by lolamtisch** [comment]
What operating system are you using?

**Comment by Key-explanation** [comment]
I am using windows 7 on my PC

**Comment by henrik9999** [comment]
> I am using windows 7 on my PC

32bit?

**Comment by Key-explanation** [comment]
Yes

**Comment by henrik9999** [comment]
yeah multiple people already reported that i just tried it on a vm too and it crashes but i cant tell from the crashlog what the issue is.
win 7 is deprecated and 32bit is old too so we are probably not going to waste anymore time on that just upgrade your pc

**Comment by UnlacedGxng** [comment]
Hi, Jus wanna say that it doesnt only happens in windows7, as I use
Brave browser
Type: Extension
Windows 10 2021-Update OS
32-Bit

I'm not sure thou, but I think it happens with all x86 Windows OS, Sooo..... ithink their are alot of x86 users, and fix this problem is highly requested.

Other things I Noticed,
As soon I start Browser in Mal extension in it, the CPU spikes to 100% in both 32 & 64Bit, Thou in 64Bit it doesn't crashes and 32bit it crashes.
The cpu spikes for around 7 seconds, and I assume its because it takes lot of cpu to load all the websites list.

I would be happy, if you think of fixing this in future, and remove the wontfix label 🙂 

Thanks.

**Comment by forsyth47** [comment]
uhh... soo umm
I actually fixed it, wont call it a fix... but some modification in source code.

so i found out it was due to lot of file in the source(src), so i jus deleted bunch of them that i dont use and compiled it...
and here is the repo for those who use 32bit pc.

https://github.com/forsyth47/MALSync

@Key-explanation
