### ISSUE TITLE
Not auto tracking anime

### ISSUE THREAD

**Issue by Key-explanation** [MALSync/MALSync#1257]
### Describe the Bug

On opening an anime, instead of tracking the current anime, it would track the previously watched anime. Then i have to manual correct anime using correction pop up

### Steps to reproduce the behavior

1.Open an anime.
2.Watch it for some time.
3.click home(click on 9anime).
4.click on an another anime.
5.the information about anime will be the same as the previous one (refering to the info in the MiniMAL and the overlay which shows score,status,episode,your score).

### Browser

chrome

### Type

Extension

### URL

www.9anime.id

**Comment by lolamtisch** [comment]
I can not reproduce it. Please add steps to reproduce the behavior.

**Comment by Key-explanation** [comment]
steps to reproduce have been added

**Comment by lolamtisch** [comment]
It does not track at all and has nothing to do with the previos tracked anime. 

9anime apparently has problems with its routing on the home page and the urls are wrong, because of the differnet url MALSync does not get injected on the page at all. If that happens reloading the page should fix it.

https://9anime.id/index.php/watch/the-devil-is-a-part-timer-season-2.6257/ep-3
instead of 
https://9anime.id/watch/the-devil-is-a-part-timer-season-2.6257/ep-3

edit: The urls seem to be correct again on 9anime. 
🤷
