### ISSUE TITLE
fullscreen on 9anime

### ISSUE THREAD

**Issue by jok1n9** [MALSync/MALSync#1307]
### Describe the Bug

fullscreen on 9anime isnt working consistently, this is especially bad because it nevers works when it automatically changes episode, which is the most important time for it to work

### Steps to reproduce the behavior

get into 9 anime, let anime episode automatically change, and it wont fullscreen

### Browser

edge chromium

### Type

Extension

### URL

9anime.id

**Comment by lolamtisch** [comment]
For some people the auto full screen is blocked because of browsers security. On chromium based browsers there is no way around. If it does not work you are out of luck.

**Comment by EmFresh** [comment]
I think I found an odd fix that seems to work on opera gx (and probably other chromium browsers). this issue only happens when auto transitioning from one episode to another so when I skipped at the end of an episode, ( when the skip time would send me further than the end of the video) when the next episode popped up it was sent to fullscreen.  I'm not sure why this works but if you could implement this automatically that would be gr8.

**Comment by henrik9999** [comment]
> I think I found an odd fix that seems to work on opera gx (and probably other chromium browsers). this issue only happens when auto transitioning from one episode to another so when I skipped at the end of an episode, ( when the skip time would send me further than the end of the video) when the next episode popped up it was sent to fullscreen. I'm not sure why this works but if you could implement this automatically that would be gr8.

this works because you clicked on the page then chrome allows fullscreen to open, so still useless because people dont want to click stuff
