### ISSUE TITLE
Add a filter option for setEpPrediction

### ISSUE THREAD

**Issue by JustArion** [MALSync/MALSync#1594]
### Suggestion

The code [here](https://github.com/MALSync/MALSync/blob/master/src/myanimelist/myanimelistClass.ts#L197) sets the predicted latest episode. 

Could a button be added somewhere to filter entries by episode watched 1 -> predicted latest episode?

Currently if you click on the "Progress" button on MAL it sorts it by highest watched episode count (regardless of the anime's latest episode)

Button Example Case:
Imagine you have a few animes
```
SomeAnime 3 / [4] 12
AnotherAnime - / [12] 12
YetAnotherAnime 3 / [3] 12
AndAStandardOne 9 / 12
```
Sorting this would allow us to see the most relevant anime (if you're watching as it releases) first.
Sorting the list would end with something like this:
```
SomeAnime 3 / [4] 12
YetAnotherAnime 3 / [3] 12
AndAStandardOne 9 / 12
AnotherAnime - / [12] 12
```
This sorts the `currentEpisode` / `predictedLatestEpisode` to those that are incomplete (or uncaught up to the latest), the `totalEpisodeCount` in this case (12 for all of them) is regarded as irrelevant.

If the feature request is out of the scope of the Extension then I'd understand and kindly close the Github issue.

**Comment by lolamtisch** [comment]
Changing the sorting will be difficult because Mal has pagination etc.
But the list in the extension popup does that by default in the watching lists. Sorted like this.
1. Airing anime with unwatched EPs
2. Airing with all EPs watched
3. Sorted by last updated.

Is that enough of an alternative?

Full sized version:
https://malsync.moe/pwa/#/book/anime/1

**Comment by JustArion** [comment]
It's a good alternative, thanks!
