### ISSUE TITLE
Add manga 📖 sites and show the latest page to continue after a anime series 

### ISSUE THREAD

**Issue by ripgamer** [MALSync/MALSync#1747]
### Add manga 📖 sites and show the latest page to continue after a anime series 

To add this feature we can use various sites and data bases to see where the original anime is left of and show this info in the manga webpage whenever user opens that perticular manga page .

We can start with adding [Manga4life](https://manga4life.com/)

**Comment by lolamtisch** [comment]
No idea what you are talking about

**Comment by farahnur42** [comment]
@ripgamer If I'm getting this right, you want 
![image](https://user-images.githubusercontent.com/37258115/232102333-6a6f20d8-bc2f-4061-8441-caae63ddee1b.png)
this information above (from My Hero Academia's MangaUpdates page in this example) to be part of the MALSync embed? 
![image](https://user-images.githubusercontent.com/37258115/232102438-54dfe029-e4c8-424e-8f0b-813bd30afa82.png)
And you want us to start with Manga4Life for this feature? 
If so, we have no MU mapping in place to make this possible currently, and I can't comment on how reasonable it would be as a feature addition otherwise.

**Comment by ripgamer** [comment]
certainly you got what I am saying...

I also don't have any api's which directly convert anime to manga chapter but this fetcher is worth working on if anyone knows any mapping api

i have searched these api though can anyone verify these api ?
[jikan api docs](https://jikan.docs.apiary.io/)

**Comment by ripgamer** [comment]
> 

The task is to add a feature to a manga website that shows the latest manga page after an anime series. This feature can be implemented using different websites and databases to find where the anime left off and display this information on the manga webpage. 
@lolamtisch

**Comment by ripgamer** [comment]
The task is to add a feature so website shows the latest manga page after an anime series.
