### ISSUE TITLE
Released episode counter not updating on some shows

### ISSUE THREAD

**Issue by ericnoble1991** [MALSync/MALSync#1783]
### Describe the Bug

I have a problem with some shows not updating. I have tried to look for a solution but could not find any info on how it works or where it gets the data from.
![image](https://user-images.githubusercontent.com/97842283/235440516-9744e5ae-60e0-498c-bcca-9bfbd7a0cf57.png)

### Steps to reproduce the behavior

No steps other that accessing anime page on MAL and Progress number in between [ and ] is incorrect

### Browser

Edge

### Type

Extension

### URL

https://myanimelist.net/anime/50431/Xiling_Jiyuan

**Comment by lolamtisch** [comment]
Our tracking possibilieties is very limited with non anime entries. As there are no torrents in the anime trackers and the streaming pages are not up to date either. There is no fix for these edgecases.

"Shows" mean multiple entries. Would be good if you could list them all so I can check if it is the same for them too.

**Comment by ericnoble1991** [comment]
Is there possibly a way to update the counter using the progress counter that updates the episode watched? It updates the counter higher than the Released Episode Counter and as it updates the MAL list could that same data not be used to update the database/source the data is pulled from? I am guessing this may be a lot to change though so may not be worth the effort.

**Comment by lolamtisch** [comment]
That would only work if everybody enters the correct episode on their list. Which is unlikely.

The 2nd entry is just that unpopular that it does not have torrents. But as a workaround you could just switch to the JP Dub in the settings. This entry at least could the "english sub" tracked correctly, as it is just because of a part that is not implemented yet. For the 1st I dont see a easy way, expect implemting a bilibili tracker, but we dont even support that page yet, so very unlikely and too much work for such seldom edge cases.
![image](https://user-images.githubusercontent.com/12599334/236268071-2165b28e-528f-4140-9931-ad2c18051bd7.png)

**Comment by lolamtisch** [comment]
It is not in the wiki, because I want the people to report it. This way I can check if it is not a real problem in the system and not just a missing data problem.
