### ISSUE TITLE
Single word custom domains are not accepted

### ISSUE THREAD

**Issue by danbulant** [MALSync/MALSync#1996]
### Describe the Bug

I'm using custom DNS solution (as part of tailscale), and I have "jellyfin" itself as a valid domain - I can type http://jellyfin and it will open up jellyfin in my browser.
The regex check in MALsync doesn't accept domains without TLDs

### Steps to reproduce the behavior

Try to add a domain without tld as a custom domain, for example http://jellyfin

### Browser

Vivaldi 6.1.3035.302 (	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)

### Type

Extension

### URL

http://jellyfin

**Comment by lolamtisch** [comment]
I will look into it. Could be that the browsers don't support it either way.

**Comment by danbulant** [comment]
It's that MALsync won't let me save the setting, as it itself has a regex that [tests domains](https://github.com/MALSync/MALSync/blob/master/src/_minimal/components/settings/settings-custom-domains.vue#L106) for validity

**Comment by louisroyer** [comment]
If you have control of what domain name is used with your custom DNS solution, a workaround is to set it to http://jellyfin.home.arpa instead of http://jellyfin
The home.arpa domain is reserved for this specific use by [RFC 8375](https://datatracker.ietf.org/doc/html/rfc8375). If your custom solution doesn't support this kind of domains, I strongly suggest you to [open an issue on tailscale](https://github.com/tailscale/tailscale/issues).

**Comment by danbulant** [comment]
Thanks.
I could just add that to my /etc/hosts or elsewhere (I also do use dnsmasq), it's just that this works already, I use it as a shortcut and MALsync is the only thing that doesn't support that, just because of a regex check in settings saving.
I didn't check, so I could be in the wrong, but I didn't see any indication of extensions not being able to request access to these kind of domains/origins.
