### ISSUE TITLE
Make it update entries that aren't in a list yet

### ISSUE THREAD

**Issue by Black-Speedy** [MALSync/MALSync#2071]
### Suggestion

I propose a feature enhancement for MAL-sync, which would enable it to synchronize the watched status across various platforms, even if the anime hasn't been added to the library on one of those platforms. Currently, if I add an anime on MAL and watch, let's say, 2 episodes, but I haven't added that same anime on Anilist with a status like 'plan to watch' or 'watching,' the synchronization doesn't occur, and the anime remains untracked on Anilist.

**Comment by lolamtisch** [comment]
This should already be the case

**Comment by Black-Speedy** [comment]
Hmm that's good then. It's just that I tested it yesterday again and it didn't seem to do it after I removed an entry completely from a list.

**Comment by Jerit3787** [comment]
It sync periodically actually. It doesn't like if you make changes here and expecting it to change on the other side instantly. If you want to instantly sync, then click the sync button manually in the settings

**Comment by DexLuther** [comment]
> It sync periodically actually. It doesn't like if you make changes here and expecting it to change on the other side instantly. If you want to instantly sync, then click the sync button manually in the settings

Correct. Websites tend to update pretty quickly based on information they receive from an API, but making changes on the website aren't alwasys updated as quickly to be available on the API.

This is probably due to traffic, cashing and to reduce/prevent cashing issues and reduce traffic and to group information changes together.

If you make a change on the Website,
It's immediately updated on the API,
Programs/services request the new information,
You realize you made a mistake,
Change the information back,
It's immediately updated on the API,
Programs/services request the new information,

That's two API requests.

If they add a slight delay, they can wait for you to enter the episodes you watched, input a score, maybe write a comment, then go back and change your mind about the score, remember that you didn't watch(or did watch) an episode and change the number, then decide to change your score again, edit your comment to fix a typo, etc and then group all that information together as an update to the API and then to watch ever programs/services request that information.

Instead

**Comment by Black-Speedy** [comment]
I'm not sure if I am misunderstanding something but if I remove an entry completely and then try to manually sync that entry doesn't show up on the site that it was removed from. 
![image](https://github.com/MALSync/MALSync/assets/78355795/7013b9cf-579f-449a-bf47-bf7700aae08f)
In this image I tested it by removing the shown anime from kitsu, and making MAL have it as an episode under the on in anilist, but kitsu doesn't show up.

**Comment by Jerit3787** [comment]
>In this image I tested it by removing the shown anime from kitsu, and making MAL have it as an episode under the on in anilist, but kitsu doesn't show up.

![image](https://github.com/MALSync/MALSync/assets/64518580/c23f7a03-8bea-4f03-b7df-eeb196949a0d)
Yeah, this sounds like an bug for kitsu apperently

**Comment by lolamtisch** [comment]
And it does not show up in the missing section?

**Comment by Black-Speedy** [comment]
To me, it seems weird because if I add it as want to watch or something else it shows up like it always
![image](https://github.com/MALSync/MALSync/assets/78355795/70b69aae-f6a2-4451-8682-6dadebf8d86c)
But if I didn't then you are correct it shows up in the missing section. I just thought it would be able to find it like it does if it is in want to wacth

**Comment by lolamtisch** [comment]
We compare watching lists and map Mal IDs to find entries that need an update.
If an entry does not exist on the users list we first have to check if kitsu even has that entry. This is done with a search on the Mal id. They are 2 different routines, that is why they are shown independent
