### ISSUE TITLE
Do Not Automatically Allow Access to All Sites

### ISSUE THREAD

**Issue by Tama47** [MALSync/MALSync#2073]
### Suggestion

The extension should only allow access to the sites you've selected, instead of automatically allowing access to all sites and video players.

<img src="https://github.com/MALSync/MALSync/assets/96937943/37bfc896-7f67-43f2-a84d-73fce357dc66">
<img src="https://github.com/MALSync/MALSync/assets/96937943/0f0c53a0-59f1-4cd0-91c1-25f48f489503">

**Comment by lolamtisch** [comment]
We would like to do that, but firefox desktop is very unstable with injecting scripts on domains it does not have directly access to on install. Firefox android does not even support adding new domains afterwards. Currently it is just not possible, lets see if with mv3 of the extension api it will be possible, but support in the browsers is currently very broken. That is why google gave up with discontinuing the mv2 support for now. 

I am not sure either why this usecase is not something the browser extension apis support. We dont even have a way to ask for permissions if you for example open a page you dont have allowed to be sure or so. I feel that it will flood our support channel with "why does it not work on page xy".

Another problem are player urls. Because they often change and multiple pages use the same video players. So it is very difficult to stay on top which page uses what player. So they will always be something that will be injected in the beginning.
