### ISSUE TITLE
[Website Request] Webtoon

### ISSUE THREAD

**Issue by SoldierZoom** [MALSync/MALSync#2142]
### Website name

Webtoon

### Website link

https://www.webtoons.com/

### Website language(s)

English, French, German, Spanish, Chinese, indonesian

### Other details

Was denied a while back cause MAL had barely any manhwa however they now allow them with most manhwa on this site on MAL too

**Comment by henrik9999** [comment]
And now it will be denied as it's impossible to get the correct chapter number on that page, because of the specials and whatever they have been between

**Comment by Keiser04** [comment]
> And now it will be denied as it's impossible to get the correct chapter number on that page, because of the specials and whatever they have been between

Couldn't you just take the one that is in the url? or from the
<h1 class="subj_episode" title="Ep. 152">Ep. 152</h1>? Or do you mean the 12.5 chapters equivalent to those in tmo?

![image](https://github.com/MALSync/MALSync/assets/146493916/c4b10ed9-de86-488c-abe0-4bd3ec7f9c0a)

**Comment by lolamtisch** [comment]
@Keiser04 The problem is that they have a very inconsistent naming scheme. 

Example: https://www.webtoons.com/en/sf/denma/list?title_no=921

**Comment by Keiser04** [comment]
> @Keiser04 The problem is that they have a very inconsistent naming scheme.
> 
> Example: https://www.webtoons.com/en/sf/denma/list?title_no=921
> 
> Additionally I think they have something like seasons where the chapter count starts at 1 again in the same series etc

I guess taking that span wouldn't go either? Note that Tower Of God counts ep 0 as 1, so there's one episode too many. The same with teenage mercenary. although with those that do have it, it's respective.

<span class="tx _btnOpenEpisodeList NPI=a:current,g:en_en">#1399</span>
![image](https://github.com/MALSync/MALSync/assets/146493916/a37cd87a-2954-4d20-b8a0-68705667e78d)
Basically that span shows what comes out on the right hand side.
![image](https://github.com/MALSync/MALSync/assets/146493916/b7aab7de-29d1-4779-9b42-bdf91e410d2d)
Although as I said it is possible that if there is chapter 0 it doesn't really count right, because it counts 0 as one as I feared.
![image](https://github.com/MALSync/MALSync/assets/146493916/31588f89-25c4-485f-980c-b41e7fe5c5dd)
