### ISSUE TITLE
Push notifications do not work properly in mobile browsers

### ISSUE THREAD

**Issue by Sickhead01** [MALSync/MALSync#2465]
### Describe the Bug

When a new episode/chapter is released for an anime/manga notifications won't come on mobile until I already have the extension open in the foreground.

Additionally even on Firefox PC same thing often happens but sometimes they come in when the browser is open but the extensions isn't open in the foreground. When i used to use Edge and Chrome (haven't in months) notifications came in even with them closed

### Steps to reproduce the behavior

Wait until you know for a fact an episode of a show on your list is available online (on Gogo or something) and you know you should have already recieved a notification from Mal-Sync by now, then open the extension and wait a few seconds. Notification comes in (but why do i have to open mal-sync to get it?). It defeats the purpose of turning on notifications to an extent.

### Browser

Firefox, Edge Canary, Kiwi (on android: Google Pixel 7). At first i thought is was a firefox issue, then i tried Edge Canary, it's buggy by nature so i tried Kiwi and the problem persists. When i was using it with Kiwi some months ago, i think before a certain Mal-Sync update, i was getting notifications even when the browser was closed.

### Type

Extension

### URL

https://malsync.moe/pwa/

**Comment by lolamtisch** [comment]
> When i used to use Edge and Chrome (haven't in months) notifications came in even with them closed  

Firefox Desktop does not have an option to continue running in the background, like chromium based browsers.

>  open the extension and wait a few seconds. Notification comes in (but why do i have to open mal-sync to get it?).  

As we ship the exact same code on all browsers (android, firefox, chromium) and it works on all others, I imagine that it is because of battery optimizations.
We register a scheduler telling the browser when to load back the extension into memory and that seems not to be respected. As the notifications show when the popup is opened, we can at least be sure that the scheduler is registered, as that is triggered by that scheduler. 
But I could not find any bugreport at firefox, so it could be something with our code, but again firefox has much bigger problems with MV3. I would need to further investigate, but dont expect it to be soon, as it is a pain to debug android extensions.

**Comment by Sickhead01** [comment]
The same thing happened with Kiwi broswer tho. It's chromium and i absolutely have batter optimalization off and it's notification  also only came in after i opened malsync in it

**Comment by lolamtisch** [comment]
Kiwi does not have full extension support and buggy. Kiwi is a bad thing to compare it to

**Comment by Sickhead01** [comment]
Then which mobile browser does Mal-Sync work properly on then? Because Firefox, Kiwi and Edge Canary are basically the only ones out there

**Comment by lolamtisch** [comment]
Firefox android is the only one that has full extension support

**Comment by Sickhead01** [comment]
Great. Looking forward to it

**Comment by i486** [comment]
Is the fix 

> Possible fix found. Will be part of the next release

Does it also works for Firefox Desktop?

**Comment by lolamtisch** [comment]
Yes

**Comment by lolamtisch** [comment]
Release 0.10.3 should fix this now. Please check
