### ISSUE TITLE
Set of optional host permissions specified by user

### ISSUE THREAD

**Issue by InsaneDoggo** [MALSync/MALSync#2594]
### Suggestion

Would be cool to be able to ask "~~chrome~~ extension" to request user defined list of URLs(patterns), e.g. as a JSON array via input field in settings.

**Reason:** It's kinda ~~crazy/unsecure~~/disturbing to give access to a huge number of sites most of which I don't use (in context of MAL extension, but may use in general). It's tedious to manually manage every site in chrome's extension page by clicking "toggle button". Editing text file (JSON) much more convenient. Also it allow users to share their predefined lists of "minimal required" sets of permissions for specific sites.

Also would be nice to have option to permanently hide or minimize (e.g. to small icon) "Missing permissions warning" which occupies a lot of space.
![image](https://github.com/user-attachments/assets/ce93fa87-b6e3-4ba7-b359-e8c2bf4803be)

**Comment by lolamtisch** [comment]
The big problem is that we do not know what video player is on what page. Multiple pages use the same player. The domains make no sense. The domains change all the time, we have to add 2-3 new domains every week. So it is not really a possibility to keep track of all of them. So the suggested "minimal required sets" will always be out of date.

That is why we never bothered on implementing an page wise permission model, as the people will need to accept all the video players either way. 

Some of the permissions are not apparent why they are needed too, so manually deciding does break some features of the extension. Enough people then end up in support chat because of that.

We would love to be able to just ask the user when he opens a page for example. So he only has the permissions he uses. But that is not possible with webextensions, without adding a permission to read all opened urls and I think that is even worse and would not even fix the video player situation.

We dont like the permissions situation either, but we do not know a better way atm. The browsers do not provide the tools for better permsisions handing.

Additionally we do not even have access to set these toggles.

**Comment by InsaneDoggo** [comment]
I understand that it's a pain to implement "page wise permissions". Actually I didn't mean that devs should maintain up to date "minimal required set".  I assumed that advanced users are able to detect player' URLs to make their own set (e.g. I'm able ^_^). So this ticket is about:

1. API for advanced users to feed their sets in JSON format to the extension
2. Ability to hide warnings about missing permissions, cuz currently extension forces user to allow all URLs even if current allowed subset is sufficient.

As of "access to toggles", If I understand correctly such functionality already implemented in the chrome extension. The key here is that User provides list of URLs to be asked by extension to grant access to them.

https://github.com/MALSync/MALSync/blob/a9a688906dc003d01857d0b0103861340dee44d1/src/utils/customDomains.ts#L111

![image](https://github.com/user-attachments/assets/d7b7c9fc-5b04-4937-b67d-811e45f9e981)

![image](https://github.com/user-attachments/assets/3f727681-05e2-44c9-9394-c07b69a1e5a2)

so algo is the following:

1. User paste JSON array -> input field(text box).
2. App parses Array and converts it to chrome API format.
3. App asks user to grant access
4. User grants permissions (clicks button).


It may feels like an unreasonably big effort to satisfy just a few advanced users. Maybe it is, although I believe such users can share their sets with friends or within their communities. 

It's true that new domains are added every week, though in context of a single site it's not that frequent. Most users are attached to 1-2 sites (in average).

Also it's possible to create tools for less advanced users to detect player URLs e.g. Extension with <all_urls> permission. The difference from MALSync is that small extension (1-2 js files) which is never updates is much more easy to trust/control/"enable only when it's needed" etc.

**Comment by lolamtisch** [comment]
> I understand that it's a pain to implement "page wise permissions". Actually I didn't mean that devs should maintain up to date "minimal required set". I assumed that advanced users are able to detect player' URLs to make their own set (e.g. I'm able ^_^). So this ticket is about:

I doubt that, as 95% of the changed/missing domains are added by us. There are region locked players and players that are only on a few episodes on the complete page. No single person can find all the domains and most people are not interessted enough to collect them as a group. I mean we often do not even get reports about missing domains, if it is not the default selected player source on the page.

> Ability to hide warnings about missing permissions, cuz currently extension forces user to allow all URLs even if current allowed subset is sufficient

We want people to accept all permissions. To make sure the extension works for them. The popup is there because in firefox you  start without any permission, so if the people do not stumble over the popup nothing works.

> It's true that new domains are added every week, though in context of a single site it's not that frequent. Most users are attached to 1-2 sites (in average).

The video player domains mostly change for the big pages. Many website use that as source, so one domain change can hit over 20 pages. So it is quite frequent for one page.

> Also it's possible to create tools for less advanced users to detect player URLs e.g. Extension with <all_urls> permission. The difference from MALSync is that small extension (1-2 js files) which is never updates is much more easy to trust/control/"enable only when it's needed" etc.

All <all_urls> extensions are a security concern and not an option for just a minor problem.

> As of "access to toggles", If I understand correctly such functionality already implemented in the chrome extension. The key here is that User provides list of URLs to be asked by extension to grant access to them.

Not 100% sure but on firefox at least they are seperate I think. The toggles are "content_script" permissions which are smaller in scope as "access" permissions, which can used for injection etc. In mv2 content_scripts did even use different url matching, which made them incompatible and a pain as you had to translate them. In mv3 they use the same matching now, but I think they are still seperate.
