### ISSUE TITLE
Separate list for animes you are rewatching

### ISSUE THREAD

**Issue by Nicebull** [MALSync/MALSync#338]
Would be nice to have a separate option in the dropdown where you can see the animes you are rewatching instead of having them appear on watching.

**Comment by lolamtisch** [comment]
MAL and kitsu dont have a rewatching state is just a checkbox. I just translate it since the last update to an new state. I only show the list how mal gives them out, it has no option to just show rewatching. I could filter it. Anilist has a rewatching state. I could add that. But I think it is not that easy to add a new state. Not the highest prirority atm.

**Comment by lolamtisch** [comment]
Anilist now has a seperate rewatching list in miniMAL
