### ISSUE TITLE
Local Sync not working

### ISSUE THREAD

**Issue by TaylorM793** [MALSync/MALSync#400]
I am using Google Chrome Version 83.0.4103.116 and Local Sync seems to not be working for me anymore. I mostly use MangaDex and I have tried to sync 3 different Manga Locally and they don't store. I set as local and it says on the bottom middle that it has read that chapter but when I go to the next chapter it resets and asks me if I want to start reading again. Manga that I already had stored seems to update fine so it is just new ones that have problems.

**Comment by lolamtisch** [comment]
Do you already use the extension for a long time? Because if yes i probably know what the Problem is. It is very likely that the storage is full and does not let you save new values. In the past i spammed to much data into it. I think the easiest way is that you join Discord and we clean up the storage together in chat.

https://discordapp.com/invite/cTH4yaw

**Comment by henrik9999** [comment]
Cosing this as solved in discord
