### ISSUE TITLE
Reaper Scan

### ISSUE THREAD

**Issue by 8227846265** [MALSync/MALSync#555]
**Describe the bug**

Setup
- Mode: Anilist
- Reading: https://reaperscans.com/comics/835576-demonic-emperor/2/149

Issue:
- Correction Search Pop-Up keeps appearing per chapter since it doesn't use Anilist as the database, instead it keeps trying to use MyAnimeList.

Screenshot:
![image](https://user-images.githubusercontent.com/66582769/103768325-3ec1c900-505d-11eb-84ec-185ae1985ba8.png)

**Additional information:**
 - Browser: Brave Browser
 - Type: Extension

**Comment by farahnur42** [comment]
Set it to No MAL if there is no AniList entry for the title, that button is a *bit* mislabeled in that it's the "send to local storage for tracking" button and the problem with go away. Also: https://anilist.co/manga/116353/ There is an AniList entry for that title, you just need to search the *native* name for it instead of the English name (that's unofficial as long as the title isn't licensed).
