### ISSUE TITLE
Sync to all trackers

### ISSUE THREAD

**Issue by Yukkun** [MALSync/MALSync#584]
I'm sorry if someone has requested or this already exists (Couldn't find any info on it though after searching).

I track my anime on both AniList and MAL because what happened to MAL API ages ago.. So would it be possible to add a feature that would allow to track what you watch on two different track sites?

I know its probably not easiest thing to implement, but it would help keep one anime list always available if sites closes their API or they just go defunct for one reason or another.

**Comment by henrik9999** [comment]
We have decided against implementing this feature.
But there is List-Sync https://github.com/MALSync/MALSync/wiki/List-Sync which will sync your list to another provider every 24 hours if you enable it in the background

**Comment by zFerry98** [comment]
I don't understand why, since the function is already active by default.
If I choose MAL as master, it updates MAL;
If I choose AniList as master, it updates AniList... So why can't it do it at the same time? Or at least update one first and then switch with the second (basically it's as if I'm both masters). I could tell if either site wasn't supported.
I just want to understand where the problem lies.

**Comment by lolamtisch** [comment]
Mostly because I dont see the point of syncing 2 pages at the same time. Because the list will be outdated/wrong the moment you dont update your list in malsync.
And added complexity. Should one be the master that overwrite everything of the others what should happen if one page fails to update etc.

**Comment by zFerry98** [comment]
> Mostly because I dont see the point of syncing 2 pages at the same time.

For the same reason mentioned above.
1. Because they are both valid but with Pros and Cons;
2. Because AniList is more "stable" but less functional (for example the custom themes that give a nice advantage and characterization);
3. MAL does not even allow 0.5 as votes but it is still the most used (just look at the number of votes in the series and you can see differences of even 100,000);
4. MAL / AniList, sometimes it is supported by other scripts but not both (in fact this script is a godsend if it added support to both);

For example, I use anilist as the main one because there are series that are 7.5 and not 7 or 8, however I don't see why I should give up MAL just for that.
There is Sync, but from what I've seen it's more of a harm than useful. I can't tell him what to "copy" from the master to the slave (in fact it raises the scores with 0.5 to +1 when maybe I really don't want them to be touched).

>  Because the list will be outdated/wrong the moment you dont update your list in malsync.

I don't get something back ...
1) Shouldn't the extension "download" the values from my anilist / mal and show them to me? So even if it doesn't update the status, nothing changes (as it should be);
2) Shouldn't the extension, after recognizing the anime, send an API command (if supported) to update the episode number just watched (x% t set)? 

It would be: first start the command for master 1, then the command for master 2.
Why should this lead to problems?
Suppose MAL is offline, so master 2 doesn't update status ... ok so what? Simply when I open MAL I will notice that it has not been updated... I open the series and update it manually. Then when the extension will re-download the values ​​in the background, it will be automatically updated with the +1 to be placed on the Site.

The problem with how you tell me things is: 
that I should use this extension as a real replacement for the official WEB interface of AniList and MAL?
This is because if now I open anilist and update a series, it misleads the extension...? If so, then I don't understand why making it so difficult.

It would not be enough to say that the extension is "slave" when it checks and updates the old data (those of the DB of the extension) with the new data (those from the AniList server) and therefore if I have updated a series on AniList, this is also rewritten on the db of the extension (as anyone would expect)?
From what I know (at least for AniList):
The extension is independent, check that I am watching an anime on one of the supported sites, see that I have exceeded x% of the time I have set, send an API command to AniList that says "Update the number of episodes viewed for that series by +1".
If the command fails, it sends a (silent) notification that it failed to update the status. At most, you insert a function that retries the command (after checking that the number has not actually been updated) every x times.

I open Chrome:
The extension downloads the most updated data for AniList and MAL (from the corresponding sites). These data are greater than what the extension "remembers", so they overwrite the old ones (ONLY if they have changed / different);
So if yesterday I had, on the extension, episode 7 as the last watched of that specific anime ... Now it will be 8 that value, because it was changed to 8 by me on the official site and because I can make sure that this is how everyone expect it to work).
Now I open a supported site and watch an anime (for the minimum time for the value to be updated).
Two commands start:
The one in API for AniList;
That (I don't know how) for MAL;
Hopefully, the values ​​are updated.
Otherwise I will get a notification about the extension telling me it failed for X reason (example, error 500 or error 404 from the site). Enough, I'll have to manually update the value at that point.
At this point it will be enough to update (in the background) the extension with the most updated values ​​from the official sites.

This is the vision I have of how it could work. i guess it doesn't work so i would like to understand why? Impossible for compatibility reasons? Too easy in words but a disaster on paper?

From how I understand instead (because actually, I think I don't understand how this extension actually works):
The extension downloads the status of the "master" list (suppose AniList) of day X.
At that point, locally, it saves that I have changed X values ​​for X series (example, I have updated two states as "dropped" and added a new series with 2 viewed episodes).
After that, it will send all the updated data to AniList (imposing itself as greater than anilist and therefore will no longer update the new values ​​that I entered by hand on the official website).
In addition, we have the function that the episodes just seen (the ones it detects) updates them immediately instead of with global synchronization (the one in the background).

If it were more or less like this ... it is certainly more comfortable and requires fewer iterations with the website ... but it is also counterproductive for the average user who expects something else (at least, asking for opinions around, so I am been told).

With this I don't want to force you to add support for this feature.
I just wanted to understand why it wasn't fully implemented given the already present support for both sites.
But from how you say it, it seems that it is not feasible because this extension works differently than I expected and therefore would have to be rewritten almost from 0.

I know that most likely you will not understand anything (since I'm not English and that's all been translated by google 🥴).

**Comment by lolamtisch** [comment]
Your lists are obviosly diverging with parts of info splitt between them. Making them useless as none of both show the state or making mal atleast outdated.

> Because AniList is more "stable" but less functional (for example the custom themes that give a nice advantage and characterization);  

Useless if data is not consistent between pages.

> MAL / AniList, sometimes it is supported by other scripts but not both (in fact this script is a godsend if it added support to both);  

Dual Sync does not fix that problem.

> (in fact it raises the scores with 0.5 to +1 when maybe I really don't want them to be touched).  

So you are using different ratings for the two pages? Rate them accordingly, 0.4 rounds down how it should be.

> Suppose MAL is offline, so master 2 doesn't update status ... ok so what?  

Data is not correct on the second list -> what is the point of dual sync if it is not correct in the end. 
And there is the problem with the error message. Should it show one or not. If yes it looks like it is failing all the time if one page is down even if it is updating the master. If it does not show an error you miss that it does not work anymore.


> that I should use this extension as a real replacement for the official WEB interface of AniList and MAL?

No i meant that it does not make much sense to use it like that, but it is the only way to have data consistency between both pages.

The remaining text I dont really understand. I think you are trying to cache failed updates until the page is back online. This will just result in wrong data if you for example watch anime on 2 different pcs.

The technical part is not as bad of a problem, but ui and userinteraction is more of a problem.

But dual sync is just bad practice as it will sooner or later result in very unconsistent lists. 

-> Choose one list and use the other as backup. Everything else does not really make sense.

Sorry but it will be difficult to convince me to add this feature. 😉

**Comment by zFerry98** [comment]
> Sorry but it will be difficult to convince me to add this feature. 😉

But the problem is that we're not really understanding each other 😂🤷‍♂️.


> Useless if data is not consistent between pages.

This is where I am not understanding ... It seems that it is forced to use the command for AniList, same identical also on MAL ... and I believe it does not work!
It is obvious that if you use a command for Linux on Windows, it will not work.
For this, I talked about 2 commands.
First the one for master 1 (in my case AniList),
then the one for the elusive master 2 (MAL).
Since if I now switch as master 1 (from AniList to MAL), and review the exact same episode, these will be rightly updated on MAL.

Why shouldn't this thing work when automated?
Is it there, does it already work if done manually by the user but cannot be automated?
If I now watch ep 2 of dragon ball z with AniList as master 1, this will be successfully added to AniList ...
I change master with MAL, I review the episode 2 of dragon ball z ... it is correctly added to MAL ...
So why can't 2 master automation be implemented?
It would be enough to run the usual commands for the selected master (anilist) and then tell it to use the commands it would use for MAL (if MAL is master 2).
![2master](https://user-images.githubusercontent.com/17975351/109650214-323d8680-7b5d-11eb-8a8d-c5a8b4b7432a.jpg)


> > MAL / AniList, sometimes it is supported by other scripts but not both (in fact this script is a godsend if it added support to both);
> 
> Dual Sync does not fix that problem.

I badly explained myself. I meant that at the moment there are scripts to manage OR ONLY AniList OR ONLY MAL .... however this script (or rather extension) is a godsend because (although not as we are talking about now) it handles both MAL and AniList.


> So you are using different ratings for the two pages? Rate them accordingly, 0.4 rounds down how it should be.

A horn!
Why do I have to change the votes I have already added?
On AniList it is 7.6 and it remains so, on MAL I decided that it does not deserve 8 but 7 ... Why do you have to update me to 8? without telling him to just ignore the votes and only update the number of episodes seen?
Sorry but I totally disagree on this point.
It is not obvious that you have to copy ALL the settings of master 1 on the slave (maybe I'm only interested in it being updated that I have simply seen an episode...... which is the reason for the dual sync request...)


> > Suppose MAL is offline, so master 2 doesn't update status ... ok so what?
> 
> Data is not correct on the second list -> what is the point of dual sync if it is not correct in the end.

Same reason that if my Master 1 is AniList and goes offline but I still watch an episode, this episode will suffer the same fate if in a situation of:
Master 1 ---> AniList (offline) ---> same error it would give me now without the dual sync update request
Master 2 ---> MAL (online) 

How does the extension behave now if AniList goes offline for 2 days and I still watch episodes in those two days?
Likewise even if I had 2 masters.



> And there is the problem with the error message. Should it show one or not. If yes it looks like it is failing all the time if one page is down even if it is updating the master. If it does not show an error you miss that it does not work anymore.

The error is such that if (rightly) one occurs, then you are notified that there has been an error (just like it does now). If there are no mistakes, it behaves as it does now ... 🤷‍♂️ I don't understand what you didn't understand.
What I meant was to show an error if (rightly) one of the two or both masters had a problem (like a 500 = AniList down) and then the extension was unable to update the list.



> The remaining text I dont really understand. I think you are trying to cache failed updates until the page is back online. This will just result in wrong data if you for example watch anime on 2 different pcs.

Honestly, not being a programmer and not too much of a computer expert ... The act of temporarily saving data to be loaded (which has not been loaded for some problem) somewhere, is it called Caching?
In that case, yes.
Otherwise right now what does the extension do if I happen to watch 30 series and 200 episodes while master 1 is offline? and then another 2 series on another pc?
It just does the same thing it does now (which I thought it was: remember you saw X ep of X series and then update the list, ONLY IF THIS HAS NOT ALREADY BEEN UPDATED).
Simply, it will have to repeat the same actions but with the commands for the master 2 (for the usual speech that you cannot use linux commands on windows).



> -> Choose one list and use the other as backup. Everything else does not really make sense.

It would make sense if you could choose what it should copy from master 1 and what it should NOT copy.

This dual Sync feature request is for this reason:

I use 2-3-4 ... 100000 lists (let's do 2 for now)

AniList and MAL:
I am interested in automating the process that if I watch "dragon ball z episode 2", both on AniList and on MAL it is updated that I have seen the episode. THAT'S ENOUGH. No ratings, descriptions, tags, etc. At most (although evident) the start and end dates and the dropped / on-hold status.
The grades and the rest will then be my problem (since MAL and AniList use different scores).


Then for the reasons of using 2 lists instead of just one I have already talked about it above:
They both have good pros and cons, ratings, CSS customization (which everyone can see), website layout, anime series present on one side but not the other, number of users who use the corresponding platform etc.

I hope I explained myself better this time. Unfortunately (with great difficulty) I think I have broadly understood how the extension works and therefore I assume it is not possible to add this feature. I still wanted to understand.
Thank you for your patience for reading so far 👍, it is still the top automation script. At this point I will have to put MAL as master 1 and manually update AniList (since at the moment my votes are being altered, WHICH I DON'T WANT, on both sides).

**Comment by soredake** [comment]
gogoanime.ai
