### ISSUE TITLE
Cannot install MALSync on firefox android

### ISSUE THREAD

**Issue by BikramKumar6928** [MALSync/MALSync#586]
I am using a recent version of firefox.
Details:-
81.1.1 (Build #2015764547)
AC: 57.0.6, bdbd5ccfd
GV: 81.0-20200917005511
AS: 61.0.13

I am unable to install the add-on from firefox add-ons site.
https://addons.mozilla.org/en-US/firefox/addon/mal-sync/

The "add to firefox" button is highlighted.

Please provide steps for 
![Screenshot_20210205-010446_Firefox](https://user-images.githubusercontent.com/24207657/106945721-2ae9af80-674e-11eb-8bb4-b6d824973f76.png)
installing it.

**Comment by lolamtisch** [comment]
Firefox blocks all extensions by default since the redesign, only a very small selection you are allowed to install. 

But it is possible to sideload extensions in Android Firefox Nightly. Just follow the tutorial below. I already create a collection so you can skip that step
Id:13616310
name:MALSync
https://www.androidpolice.com/2020/09/30/firefox-for-android-brings-back-general-extensions-support-heres-how-to-set-it-up/

**Comment by BikramKumar6928** [comment]
Hi @lolamtisch ,

Thanks for such quick response.

I checked and was able to install the extension.

Just a note for anyone reading, you cannot install other extensions while the custom addon is active. So remove it after installing the extension to see the other extensions.
