### ISSUE TITLE
is permission system change worth looking into?

### ISSUE THREAD

**Issue by musbah** [MALSync/MALSync#659]
Hello, I feel like there are just way too many permissions "on" by default right now. And I was wondering if that was worth changing. 
I used to work on an addon that would have essentially done what this is doing (it sucks though...) and the way it asked for permissions was a bit different. 
What I essentially did was have something like 
`"optional_permissions": [
    "*://*/*"
]` 
in the manifest and then in the code I used something like 
`permissions.request("host")`
 when actually visiting a specific host on the list so that it only asks for permissions once and then if it's approved then great, it never asks again. 

 This would also get rid of all the manual permissions that need to be approved every update when adding new websites.

Anyway, I don't mind looking into this and creating a pull request myself, I was just wondering if it is something that anyone else thinks is worth doing.

**Comment by lolamtisch** [comment]
For the Custom domain feature we already have most of the system you describe in place and I though about it too, but I am not sure if it is really worth it. 

The problems I see:
- The Webnavigation Permission is needed, which in my book is 10x worse transparency wise than 10000 single domains.
- I only see two ways how to accept the permissions. You hope that they open the popup click there on a button or with notifications. But notifications are kind of weird for something like this, specialy on Android and Firefox where there are no buttons on notifications.
- Specially in the beginning they will be spamed a lot. Open the page -> notification, open video page -> notification for the video provider, changing source because slow loading video and again a notification.
- Confusing notifications. For example they watch an western movie on an totally unrelated page, but they use the same video provider, then they will get an notification. It is correct, but it will be confusing for the users.

Pros:
- we could update the domain list on the fly and don't need to wait for the next release.
- No permission notifications between releases.

I am really not sure on this one. If it would not hurt more than help in the end.

**Comment by musbah** [comment]
Yeah, you do have a point. I honestly didn't think about the providers and the need for Webnavigation at all... We could technically show a list of the site permissions on install , and let users tick/untick them. It would kind of mitigate some of your concerns while giving people some options, but I'm not sure if that would even be worth doing, would probably still be confusing to the average user.

**Comment by lolamtisch** [comment]
I think i am closing this for now then.
