### ISSUE TITLE
[Feature Request] Support for Drama, Movie or Series other than anime

### ISSUE THREAD

**Issue by SaruDesu** [MALSync/MALSync#709]
It would be great if you can also add support for other entertainment content other than anime as this extension already supports Simkl which supports tracking of other series and movies. Because afaik there is no publicly known extension that supports automatic sync on dramas or series especially asian ones.

**Comment by lolamtisch** [comment]
The Extension is specially build for anime and manga. It is not really feasable to add other media, as they would need seperate tracking site implementations, specially the configuration for the user would be a nightmare. The api for anime in Simkl is seperate of the the series/movies, so that would need to be implemented too. 

They are just too different and not compatible in how the extension works. This would need to be an seperate extension. But I dont have the time/motivation for that.

If any dev is interested in creating and maintaining such an extension, then I would happily abstract core functionalities so that it can be used by both extensions.
