### ISSUE TITLE
Update both MAL and Kitsu at the same time?

### ISSUE THREAD

**Issue by sprite-1** [MALSync/MALSync#71]
Kitsu's built in MAL sync is forever broken so if possible, it would be nice if the script updates both the Kitsu and MAL account at the same time 😅️

**Comment by lolamtisch** [comment]
Multisync will probably never come, as it is too unreliable in my opinion. 
But list mirroring like on kitsu between the 3 pages is on my Todos. Just not top Priority atm.

**Comment by sprite-1** [comment]
What do you mean by list mirroring? How would it differ from dual update? If I have to guess, is it something where, at a set interval, it will synchronize the full list in one go instead of updating it per episode/chapter?

**Comment by lolamtisch** [comment]
Exactly that. It goes throw the complete list and makes sure that it is the same. 

Advances are kind of clear I would say.
Entries are the same even if not synced with dual update.

And if one of the pages fails to sync in Dual-Update. How should that be handled? 
So list mirroring sounds easier to implement to me than Dual-Update. As I have the code for retrieving the lists already.

**Comment by sprite-1** [comment]
Yeah I agree, Kitsu is kind of my secondary site for keeping track of things so it's not a big deal if it isn't real-time along with MAL. Since it's not top priority atm, I'll just keep an eye out for when it eventually comes :+1: thanks for the awesome script!

**Comment by lolamtisch** [comment]
@sprite-1 
The new release contains the first alpha of the list mirroring.
https://github.com/lolamtisch/MALSync/wiki/List-Sync

**Comment by SleeplessSloth** [comment]
Is it possible to sync to another site rather than Kitsu? I primarily use Anilist but having MyAnimeList synced up would be awesome

**Comment by lolamtisch** [comment]
@SleeplessSloth 
The sync works for anilist/kitsu/MAL and simkl. Just make sure to set the extension to your primary list, in this case Anilist and then it can be synced to MAL and every other of the services you authenticated in the extension.
![image](https://user-images.githubusercontent.com/12599334/66257014-62300100-e794-11e9-9429-bebbed14fafb.png)

Since the newest version 0.6.5 malsync can sync the lists in the background too if enabled.

**Comment by SleeplessSloth** [comment]
Strange, I have it set to AniList as the primary list but when I click on List Sync in the ETC settings, it shows a popup with a link to authenticate on Kitsu and nothing else happens. I'm still on 0.6.4 though but I'll try to investigate. Thanks!

**Comment by lolamtisch** [comment]
@SleeplessSloth 
Are you loged in on the MAL website?

The easiest thing would be if you passes by our discord text chat server: https://discordapp.com/invite/cTH4yaw

**Comment by sprite-1** [comment]
When I click on Sync, the pop out to click for authentication vanishes too quickly and by the end, I only have the Simkl link because the rest have disappeared already.

![1570314259676](https://user-images.githubusercontent.com/33685433/66261562-5418c980-e802-11e9-97da-5657a831e045.gif)

**Comment by lolamtisch** [comment]
You can allways change the sync mode of the main extension and authenticate there and then switch back. It is still alpha and some planned rewrites will make it a bit easier to use in the future.

For Mal you only need to be logged on the site like normal. Make sure you browser does not have some extreme privacy features enabled that block cookies

**Comment by sprite-1** [comment]
Okay, but does it not auto-add items that are not in the other list? I noticed that when I synced it up, it only updated some anime. For example, To Aru didn't sync but as soon as I added To Aru manually on Anilist and synced again, it updated it properly from my MAL

**Comment by lolamtisch** [comment]
It should appear in the second list on the sync page and then it should get synced. Only from the main list to the slave list not the other way around.

**Comment by plW0lf** [comment]
I see that this issue is still in progress.
I think that multisync could work great if it was made that in MALSync window in status section would be added "Additional Sync" button. After pressing it, additional window would appear in which user would be able to approve other website or correct them (like correction popup). The way multisync should work I think, that it reads first main list and marks watched/read episodes. If server is down it uses source of second highest priority (so maybe list priority option in settings?). For marking episodes, it should mark them just like priority has been set.

As for list sync - It is great, but many times It just connected incorrect manga (once time it even connected simple Slice of Life with Yaoi manga -_- I guess someone inserted incorrect ID...) so some sort of controlled multisync surely would be much safer.

**Comment by lolamtisch** [comment]
https://github.com/MALSync/MALSync/wiki/List-Sync
