### ISSUE TITLE
Anime score, status, episode status and our rating above episode list instead of anime info. (animixplay.to)

### ISSUE THREAD

**Issue by akshatsi** [MALSync/MALSync#741]

**Comment by lolamtisch** [comment]
They are now on the overview page.

**Comment by platinumgamer** [comment]
I think it was better when the MAL-Sync info was displayed underneath the current video/ep as described in this issue. Is there a way to go back to how it was @lolamtisch? Was this change on MAL-Sync's side or AniMixPlay's side? Thanks.

**Comment by lolamtisch** [comment]
No not possible

**Comment by platinumgamer** [comment]
Why not? Just curious

**Comment by lolamtisch** [comment]
What exactly is the usecase when you are watching an episode. Changing the episode count makes no sense as you are watching an episode. Changing the watching state makes no sense as you are watching an episode and malsync asks you to change the state if needed. Changing the score, i dont think someone wants to set the score mid season and on the last episode malsync asks for the scrore already. 
On top of that users could think you are suposed to manually update the episode number and that it does not autoupdate.
And I dont need to think to much about changing data on MAL during video playback.

To me it just does not make much sense in the current useflow and normaly when you browsing a website you want to open the overview page to see more info to the anime and then it makes sense to have the UI there.

And you can always click on the button on the lower right to open the popup where you can update the entry. If i missed some usecase just let me know, but i think there is none that would change my view on the matter.

**Comment by platinumgamer** [comment]
Those are all very good points. Personally, I enjoyed the old style for the following reasons:
AniMixPlay's tracking is not as good as MAL-Syncs. It displays the last episode you started instead of the last episode you finished. Therefore, I would always look at my last episode number in the old MAL-Sync bar and choose the correct episode directly underneath. 

I actually do update the score a few episodes in using the old MAL-Sync bar. I also change the score at the end of the season if my opinions changed too.

Both of these situations can be solved by manually clicking the button in the bottom right as you've said as well as several other methods but all of these require extra clicking/navigation.
