### ISSUE TITLE
Manga Sync Last Page {{feature request}}

### ISSUE THREAD

**Issue by Vinickw** [MALSync/MALSync#853]
I used to use MyMangaDex, but as it doesn't work anymore, I started using MAL Sync. But there's a feature that I miss a lot, update my manga list when I reach the last page. Would it be possible to add?

**Comment by lolamtisch** [comment]
The Problem is that there is no standard like for video players. So we would have to implement something for every page and hope that it does not break. Which would be bad as we can not do more than an update once a month.

Either way as the mangadex UI is not final it makes no sense to implement it now. I will look into this feature again when the UI gets stable.

**Comment by lolamtisch** [comment]
Some pages have the feature now
