### ISSUE TITLE
9anime.to refused auto full screen for Vidstream and Mycloud

### ISSUE THREAD

**Issue by AbyssalAssassin1010** [MALSync/MALSync#982]
**Describe the bug**

**Steps to reproduce the behavior:**
1. Select any desired title for watching.
2. Upon page load, video of Vidstream or Mycloud doesn't enter full screen mode.

**Additional information:**
 - Browser: Chrome
 - Type: Extension
 - Url: 9anime.to

**Comment by lolamtisch** [comment]
We have a few users saying the same. But we can not reproduce it. The Problem is and always has been, that fullscreen mode can not be started without user interaction (click or button press). But apparently clicking on the start button on the players stopped to be enough for chrome for a few users. For me it still works as always and i have no idea what the problem is.

**Comment by drhouse** [comment]
> 2. Upon page load, video of Vidstream or Mycloud doesn't enter full screen mode.

if you want, feel free to use my userscript: 

**Description** 
Automatically plays Vidstream and MyCloud videos in auto-fullscreen, skip opening titles hotkey (advance 90s forward), skip to next episode.

[9anime Bingewatcher+](https://greasyfork.org/en/scripts/401339-9anime-bingewatcher)

**Comment by lolamtisch** [comment]
It uses the exact same code as MALSync. So it probably has the same problem, but no idea.
